CREATE TABLE WAREHOUSE (
  W_ID INT64 NOT NULL,
  W_NAME STRING(16),
  W_STREET_1 STRING(32),
  W_STREET_2 STRING(32),
  W_CITY STRING(32),
  W_STATE STRING(2),
  W_ZIP STRING(9),
  W_TAX FLOAT64,
  W_YTD FLOAT64
) PRIMARY KEY (W_ID);

CREATE TABLE DISTRICT (
  D_ID INT64 NOT NULL,
  D_W_ID INT64 NOT NULL,
  D_NAME STRING(16),
  D_STREET_1 STRING(32),
  D_STREET_2 STRING(32),
  D_CITY STRING(32),
  D_STATE STRING(2),
  D_ZIP STRING(9),
  D_TAX FLOAT64,
  D_YTD FLOAT64,
  D_NEXT_O_ID INT64,
  CONSTRAINT D_FKEY_W FOREIGN KEY (D_W_ID) REFERENCES WAREHOUSE (W_ID)
) PRIMARY KEY (D_W_ID, D_ID);

CREATE TABLE ITEM (
  I_ID INT64 NOT NULL,
  I_IM_ID INT64,
  I_NAME STRING(32),
  I_PRICE FLOAT64,
  I_DATA STRING(64)
) PRIMARY KEY (I_ID);

CREATE TABLE CUSTOMER (
  C_ID INT64 NOT NULL,
  C_D_ID INT64 NOT NULL,
  C_W_ID INT64 NOT NULL,
  C_FIRST STRING(32),
  C_MIDDLE STRING(2),
  C_LAST STRING(32),
  C_STREET_1 STRING(32),
  C_STREET_2 STRING(32),
  C_CITY STRING(32),
  C_STATE STRING(2),
  C_ZIP STRING(9),
  C_PHONE STRING(32),
  C_SINCE TIMESTAMP NOT NULL,
  C_CREDIT STRING(2),
  C_CREDIT_LIM FLOAT64,
  C_DISCOUNT FLOAT64,
  C_BALANCE FLOAT64,
  C_YTD_PAYMENT FLOAT64,
  C_PAYMENT_CNT INT64,
  C_DELIVERY_CNT INT64,
  C_DATA STRING(500),
  CONSTRAINT C_FKEY_D FOREIGN KEY (C_D_ID, C_W_ID) REFERENCES DISTRICT (D_ID, D_W_ID)
) PRIMARY KEY (C_W_ID, C_D_ID, C_ID);

CREATE INDEX IDX_CUSTOMER ON CUSTOMER (C_W_ID, C_D_ID, C_LAST);

CREATE TABLE HISTORY (
  H_C_ID INT64 NOT NULL,
  H_C_D_ID INT64 NOT NULL,
  H_C_W_ID INT64 NOT NULL,
  H_D_ID INT64 NOT NULL,
  H_W_ID INT64 NOT NULL,
  H_DATE TIMESTAMP NOT NULL,
  H_AMOUNT FLOAT64,
  H_DATA STRING(32),
  CONSTRAINT H_FKEY_C FOREIGN KEY (H_C_ID, H_C_D_ID, H_C_W_ID) REFERENCES CUSTOMER (C_ID, C_D_ID, C_W_ID),
  CONSTRAINT H_FKEY_D FOREIGN KEY (H_D_ID, H_W_ID) REFERENCES DISTRICT (D_ID, D_W_ID)
) PRIMARY KEY (H_W_ID, H_D_ID, H_C_W_ID, H_C_D_ID, H_C_ID, H_DATE);

CREATE TABLE STOCK (
  S_I_ID INT64 NOT NULL,
  S_W_ID INT64 NOT NULL,
  S_QUANTITY INT64 NOT NULL,
  S_DIST_01 STRING(32),
  S_DIST_02 STRING(32),
  S_DIST_03 STRING(32),
  S_DIST_04 STRING(32),
  S_DIST_05 STRING(32),
  S_DIST_06 STRING(32),
  S_DIST_07 STRING(32),
  S_DIST_08 STRING(32),
  S_DIST_09 STRING(32),
  S_DIST_10 STRING(32),
  S_YTD INT64,
  S_ORDER_CNT INT64,
  S_REMOTE_CNT INT64,
  S_DATA STRING(64),
  CONSTRAINT S_FKEY_I FOREIGN KEY (S_I_ID) REFERENCES ITEM (I_ID),
  CONSTRAINT S_FKEY_W FOREIGN KEY (S_W_ID) REFERENCES WAREHOUSE (W_ID)
) PRIMARY KEY (S_W_ID, S_I_ID);

CREATE TABLE ORDERS (
  O_ID INT64 NOT NULL,
  O_C_ID INT64,
  O_D_ID INT64 NOT NULL,
  O_W_ID INT64 NOT NULL,
  O_ENTRY_D TIMESTAMP NOT NULL,
  O_CARRIER_ID INT64,
  O_OL_CNT INT64,
  O_ALL_LOCAL INT64,
  CONSTRAINT O_FKEY_C FOREIGN KEY (O_C_ID, O_D_ID, O_W_ID) REFERENCES CUSTOMER (C_ID, C_D_ID, C_W_ID)
) PRIMARY KEY (O_W_ID, O_D_ID, O_ID);

CREATE INDEX IDX_ORDERS ON ORDERS (O_W_ID, O_D_ID, O_C_ID);

CREATE TABLE NEW_ORDER (
  NO_O_ID INT64 NOT NULL,
  NO_D_ID INT64 NOT NULL,
  NO_W_ID INT64 NOT NULL,
  CONSTRAINT NO_FKEY_O FOREIGN KEY (NO_O_ID, NO_D_ID, NO_W_ID) REFERENCES ORDERS (O_ID, O_D_ID, O_W_ID)
) PRIMARY KEY (NO_D_ID, NO_W_ID, NO_O_ID);

CREATE TABLE ORDER_LINE (
  OL_O_ID INT64 NOT NULL,
  OL_D_ID INT64 NOT NULL,
  OL_W_ID INT64 NOT NULL,
  OL_NUMBER INT64 NOT NULL,
  OL_I_ID INT64,
  OL_SUPPLY_W_ID INT64,
  OL_DELIVERY_D TIMESTAMP,
  OL_QUANTITY INT64,
  OL_AMOUNT FLOAT64,
  OL_DIST_INFO STRING(32),
  CONSTRAINT OL_FKEY_O FOREIGN KEY (OL_O_ID, OL_D_ID, OL_W_ID) REFERENCES ORDERS (O_ID, O_D_ID, O_W_ID),
  CONSTRAINT OL_FKEY_S FOREIGN KEY (OL_I_ID, OL_SUPPLY_W_ID) REFERENCES STOCK (S_I_ID, S_W_ID)
) PRIMARY KEY (OL_W_ID, OL_D_ID, OL_O_ID, OL_NUMBER);

CREATE INDEX IDX_ORDER_LINE_TREE ON ORDER_LINE (OL_W_ID, OL_D_ID, OL_O_ID);
